2024-02-20 01:04:41,865: root: INFO: MLTrader : Executing the initialize lifecycle method
2024-02-20 01:04:43,746: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2024-02-20 01:04:43,747: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:43,749: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2024-02-20 01:04:43,749: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:43,750: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:43[0m
2024-02-20 01:04:43,751: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:43,762: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,156: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,158: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,163: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,166: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,167: root: INFO: Current backtesting datetime 2023-12-16 09:30:00-05:00
2024-02-20 01:04:45,169: root: INFO: Current backtesting datetime 2023-12-18 08:30:00-05:00
2024-02-20 01:04:45,170: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,173: root: INFO: Current backtesting datetime 2023-12-18 09:30:00-05:00
2024-02-20 01:04:45,173: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,174: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,174: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,176: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,298: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,300: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,307: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,309: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,310: root: INFO: Current backtesting datetime 2023-12-19 09:30:00-05:00
2024-02-20 01:04:45,312: root: INFO: Current backtesting datetime 2023-12-19 08:30:00-05:00
2024-02-20 01:04:45,312: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,314: root: INFO: Current backtesting datetime 2023-12-19 09:30:00-05:00
2024-02-20 01:04:45,314: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,315: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,316: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,318: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,436: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,438: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,444: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,446: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,447: root: INFO: Current backtesting datetime 2023-12-20 09:30:00-05:00
2024-02-20 01:04:45,449: root: INFO: Current backtesting datetime 2023-12-20 08:30:00-05:00
2024-02-20 01:04:45,450: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,453: root: INFO: Current backtesting datetime 2023-12-20 09:30:00-05:00
2024-02-20 01:04:45,453: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,455: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,455: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,457: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,580: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,582: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,588: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,591: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,591: root: INFO: Current backtesting datetime 2023-12-21 09:30:00-05:00
2024-02-20 01:04:45,593: root: INFO: Current backtesting datetime 2023-12-21 08:30:00-05:00
2024-02-20 01:04:45,593: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,595: root: INFO: Current backtesting datetime 2023-12-21 09:30:00-05:00
2024-02-20 01:04:45,595: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,597: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,598: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,601: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,741: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,743: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,748: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,752: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,752: root: INFO: Current backtesting datetime 2023-12-22 09:30:00-05:00
2024-02-20 01:04:45,754: root: INFO: Current backtesting datetime 2023-12-22 08:30:00-05:00
2024-02-20 01:04:45,755: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,757: root: INFO: Current backtesting datetime 2023-12-22 09:30:00-05:00
2024-02-20 01:04:45,757: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,758: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,758: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,760: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,887: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,889: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:45,894: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:45,896: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:45,896: root: INFO: Current backtesting datetime 2023-12-23 09:30:00-05:00
2024-02-20 01:04:45,898: root: INFO: Current backtesting datetime 2023-12-26 08:30:00-05:00
2024-02-20 01:04:45,898: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:45,900: root: INFO: Current backtesting datetime 2023-12-26 09:30:00-05:00
2024-02-20 01:04:45,901: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:45,903: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:45[0m
2024-02-20 01:04:45,903: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,905: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:45,996: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:45,998: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:46,004: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:46,006: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:46,007: root: INFO: Current backtesting datetime 2023-12-27 09:30:00-05:00
2024-02-20 01:04:46,011: root: INFO: Current backtesting datetime 2023-12-27 08:30:00-05:00
2024-02-20 01:04:46,012: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:46,013: root: INFO: Current backtesting datetime 2023-12-27 09:30:00-05:00
2024-02-20 01:04:46,014: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:46,015: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:46[0m
2024-02-20 01:04:46,016: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,018: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,162: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:46,163: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:46,170: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:46,172: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:46,173: root: INFO: Current backtesting datetime 2023-12-28 09:30:00-05:00
2024-02-20 01:04:46,174: root: INFO: Current backtesting datetime 2023-12-28 08:30:00-05:00
2024-02-20 01:04:46,174: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:46,176: root: INFO: Current backtesting datetime 2023-12-28 09:30:00-05:00
2024-02-20 01:04:46,176: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:46,178: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:46[0m
2024-02-20 01:04:46,178: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,180: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,307: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:46,309: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:46,314: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:46,317: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:46,318: root: INFO: Current backtesting datetime 2023-12-29 09:30:00-05:00
2024-02-20 01:04:46,320: root: INFO: Current backtesting datetime 2023-12-29 08:30:00-05:00
2024-02-20 01:04:46,321: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:46,323: root: INFO: Current backtesting datetime 2023-12-29 09:30:00-05:00
2024-02-20 01:04:46,324: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:46,325: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2024-02-20 01:04:46[0m
2024-02-20 01:04:46,325: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,326: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2024-02-20 01:04:46,473: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2024-02-20 01:04:46,475: root: ERROR: Traceback (most recent call last):
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 808, in run
    self._run_trading_session()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 759, in _run_trading_session
    self._on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 283, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 307, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\strategies\strategy_executor.py", line 377, in _on_trading_iteration
    on_trading_iteration()
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\AppData\Local\Programs\Python\Python312\Lib\site-packages\lumibot\tools\decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tooma\OneDrive\Documents\GitHub\coinbase-advanced-py\tradingbot.py", line 54, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2024-02-20 01:04:46,480: root: INFO: MLTrader : Executing the on_bot_crash event method
2024-02-20 01:04:46,483: root: INFO: MLTrader : [34mSleeping for 86400 seconds[0m
2024-02-20 01:04:46,485: root: INFO: Current backtesting datetime 2023-12-30 09:30:00-05:00
2024-02-20 01:04:46,487: root: INFO: Current backtesting datetime 2024-01-02 08:30:00-05:00
2024-02-20 01:04:46,487: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2024-02-20 01:04:46,489: root: INFO: Current backtesting datetime 2024-01-02 09:30:00-05:00
2024-02-20 01:04:46,489: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2024-02-20 01:04:46,492: root: INFO: Current backtesting datetime 2024-01-02 15:55:00-05:00
2024-02-20 01:04:46,493: root: INFO: MLTrader : Executing the before_market_closes lifecycle method
2024-02-20 01:04:46,494: root: INFO: Current backtesting datetime 2024-01-02 16:00:00-05:00
2024-02-20 01:04:46,494: root: INFO: MLTrader : Executing the after_market_closes lifecycle method
2024-02-20 01:04:46,494: root: INFO: MLTrader : Executing the on_strategy_end lifecycle method
2024-02-20 01:04:46,495: backtest_stats: INFO: Backtest took 0:00:04.638500 for a speed of 0.000
2024-02-20 01:04:46,495: root: WARNING: Cannot plot returns because the strategy returns are missing
2024-02-20 01:04:46,694: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
